### ISSUE TITLE
Add `whitelistedDomains` field in analytics database

### ISSUE THREAD

**Issue by xitronix** [arcxmoney/analytics-sdk#86]

**Comment by xitronix** [comment]
```
use analytics
db.projects.updateMany({}, {$set: { whitelist_domains: []}}) 
```
run it in staging and prod

**Comment by xitronix** [comment]
@kQuintal add fields in prod as well, please

**Comment by kQuintal** [comment]
All done ✅ 
<img width="312" alt="image" src="https://user-images.githubusercontent.com/10551754/208757809-2e725131-5278-4d8c-84f3-851d9ea37f4a.png">
