### ISSUE TITLE
Remove cleaning storage to avoid invalid identity id on client's side

### ISSUE THREAD

**Issue by xitronix** [arcxmoney/analytics-sdk#96]

**Comment by gtupak** [comment]
Context: https://github.com/arcxmoney/analytics-sdk/pull/95/files#diff-54ba88aa09fe0453d25d41885b902a34a01be9eb20bbececc2d6008de80e16ddR395

**Comment by gtupak** [comment]
@xitronix why is this issue blocked?

**Comment by xitronix** [comment]
@gtupak  It is blocked by the due date. We can do it in my approximation in February 2023

**Comment by gtupak** [comment]
got it!

**Comment by gtupak** [comment]
Can you add a description in this issue to explain why we need to wait till Feb 2023?

**Comment by xitronix** [comment]
That's my assumption that during this month all incorrectly saved keys will be cleaned
